frontend/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="index"),
]

ramen/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('api/bowl/', views.BowlListCreate.as_view()),
]

ramen_hunt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('ramen.urls')),
    path('', include('frontend.urls')),
]

users/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
]

ramen/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Bowl(models.Model):
    name = models.CharField(max_length=50)
    comment = models.TextField()
    date_added = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE)

    # Style choices
    TONKOTSU = 'Tonkotsu'
    MISO = 'Miso'
    SHOYU = 'Shoyu'
    SHIO = 'Shio'
    OTHER = 'Other'

    STYLE_CHOICES = [
        (TONKOTSU, 'Tonkotsu'),
        (MISO, 'Miso'),
        (SHOYU, 'Shoyu'),
        (SHIO, 'Shio'),
        (OTHER, 'Other'),
    ]

    style = models.CharField(
        max_length=20,
        choices=STYLE_CHOICES,
    )

    # Rating choices
    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4
    FIVE = 5

    RATING_CHOICES = [
        (ONE, '1'),
        (TWO, '2'),
        (THREE, '3'),
        (FOUR, '4'),
        (FIVE, '5'),
    ]

    rating = models.IntegerField(
        choices=RATING_CHOICES,
    )

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

frontend/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'frontend/index.html')

ramen/views.py
from .models import Bowl
from .serializers import BowlSerializer
from rest_framework import generics, filters


class BowlListCreate(generics.ListCreateAPIView):
    queryset = Bowl.objects.all()
    serializer_class = BowlSerializer
    # allows filtering DRF API by date added
    filter_backends = [filters.OrderingFilter]
    ordering_fields = ['date_added']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

frontend/templates/frontend/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'frontend/style.css' %}">

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ramen Log</title>
</head>

<body>
    {% if user.is_authenticated %}
        <a href="{% url "users:logout" %}">Logout</a>
        <div id="app">
            <!-- React will load here -->
        </div>
    {% else %}
        <a href="{% url "users:login" %}">Login</a>
        <a href="{% url "users:register" %}">Register</a>
    {% endif %}
    <script>
        window.django = {
            user: {
                id: "{{ request.user.id }}"
            }
        };
    </script>
</body>
{% load static %}
<script src="{% static "frontend/main.js" %}"></script>

</html>

users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    <legend>Login form</legend>
    {{ form.as_p }}
    <button name="submit">Login</button>
    <div>
        <small>
            Do you need an account? <a href="{% url 'users:register' %}">Register</a>
        </small>
    </div>
</form>

users/templates/users/logout.html
<h2>You have been logged out</h2>

<a href="{% url 'users:login' %}">Login again</a>

users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    <legend>Registration form</legend>
    {{ form.as_p }}
    <button name="submit">Register</button>
    <div>
        <small>
            Already have an account? <a href="{% url 'users:login' %}">Login</a>
        </small>
    </div>
</form>